title: Mason's Website
description: > # this means to ignore newlines until "baseurl:"
  The personal website for Mason Prey.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mprey.github.io"

# Author Settings
author: Mason Prey # add your name
author-img: me.jpg # add your photo
about-author: I am a quantiative developer at a hedge fund. Writing about random topics.
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: mprey
social-linkedin: masonprey
social-email: masonprey7@gmail.com

# Disqus
discus-identifier: mprey

# Tracker
analytics: G-CYYKNJ0PMD # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
